server:
  port: 8090
  servlet:
    context-path: /demo

spring:
  datasource:
    master:
      # 使用默认HikariPool作为数据库连接池
      jdbcurl: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      # 使用druid作为数据库连接池
      url: jdbc:mysql://127.0.0.1:3306/demoslave?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    read: get,select,count,list,query,find
    write: add,create,update,delete,remove,insert

    # druid相关配置
    druid:
      # 监控统计拦截的filters
      filters: stat,wall
      # 配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 60000
      # 间隔多久进行一次检测 检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache 并指定每个连接上PSCache的大小 oracle设为true mysql设为false 分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 10000
    # Redis默认情况下有16个分片 默认是 0
    database: 0
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0


#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.dao.entity
  configuration.map-underscore-to-camel-case: true

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check







