server:
  port: 8090
  servlet:
    context-path: /demo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.dao.entity
  configuration.map-underscore-to-camel-case: true
logging:
  level:
    com.demo.dao.mapper: DEBUG




