server:
  port: 8080
  context-path: /galanzOauth

spring:
  datasource:
    username: root
    password: Edo&123456
    url: jdbc:mysql://47.107.158.20:3306/galanz_oauth?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  redis:
    port: 6379
    host: 47.107.158.20
    password: edo9567
  aop:
    auto: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
